### gas adjustment - multiplier for the expected amount of gas
contract_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
# query rpcs for prices
query_rpcs = ["api.devnet-n1.ojo-devnet.node.ojo.network:9090","api.devnet-n0.ojo-devnet.node.ojo.network:9090"]
# event rpc to subscribe for new block and set fx rate event
event_rpcs = ["http://localhost:26657","https://rpc.devnet-n1.ojo-devnet.node.ojo.network:443"]
# event type string to check when new blocks are produced
event_type = "ojo.oracle.v1.EventSetFxRate"

event_timeout = "10s"
query_timeout = "5000ms"

gas_adjustment = 1.5
timeout_height = 10
gas_prices = "0.2stake"
# set median duration to 0 to disable posting medians
median_duration = 1
# resolve duration is the estimated delay between price updates on the contract
resolve_duration = "1000ms"
missed_threshold = 2
#default median data and ref request id at start/restart
median_request_id = 0
request_id = 0

[restart]
auto_id = true
denom = "ATOM"

### account & chain-id for the wasmd relayer account
[account]
address = "wasm1usr9g5a4s2qrwl63sdjtrs2qd4a7huh6qksawp"
chain_id = "wasm-test"
acc_prefix = "wasm"
### keyring for the relayer account on the wasmd chain
[keyring]
backend = "test"
dir = "./"

### rpc endpoint for the wasm Chain
[rpc]
rpc_timeout = "2000ms"
query_endpoint = "api.devnet-cw.ojo-devnet.node.ojo.network:9090"
tmrpc_endpoint = "http://localhost:26657"
