### gas adjustment - multiplier for the expected amount of gas
contract_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
query_rpc = "api.devnet-n0.ojo-devnet.node.ojo.network:9090"
gas_adjustment = 1.5
timeout_height = 10
gas_prices = "0.2stake"
# set median duration to 0 to disable posting medians
median_duration = 0
### account & chain-id for the wasmd relayer account
[account]
address = "wasm1usr9g5a4s2qrwl63sdjtrs2qd4a7huh6qksawp"
chain_id = "wasm-test"
acc_prefix = "wasm"
### keyring for the relayer account on the wasmd chain
[keyring]
backend = "test"
dir = "./"

### rpc endpoint for the wasm Chain
[rpc]
grpc_endpoint = "0.0.0.0:8080"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"
