name: Lint
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  lint-relayer:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            cw-relayer/**/**.go
            cw-relayer/go.mod
            cw-relayer/go.sum

      - uses: actions/setup-go@v3
        if: env.GIT_DIFF
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: cw-relayer/go.sum

      - name: golangci-lint main
        uses: golangci/golangci-lint-action@v3
        if: env.GIT_DIFF
        with:
          version: latest
          args: --timeout 8m
          working-directory: cw-relayer


  solhint-contract:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            evm/contracts/*
            evm/test/*
            evm/*

      - name: Install packages
        if: env.GIT_DIFF
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install solhint
        if: env.GIT_DIFF
        run: |
          npm install solhint

      - name: Run solhint
        if: env.GIT_DIFF
        run: |
          make lint-contract
